config/routes.rb
TrainingRubyAjisuharyo::Application.routes.draw do

  resources :articles, :categories, :comments, :countries, :products, :users, :sessions
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"  
  get "log_out" => "sessions#destroy", :as => "log_out"
  root :to => "articles#index"

  get "articles/index"
  get "sessions/new"

  namespace :admin do
    resources :articles, :categories, :comments, :countries, :products, :users, :sessions
    get "sign_up" => "users#new", :as => "sign_up"
    get "log_in" => "sessions#new", :as => "log_in"  
    get "log_out" => "sessions#destroy", :as => "log_out"
  end
end

app/models/article.rb
class Article < ActiveRecord::Base 
  attr_accessible :title, :description, :rating, :user_id

  has_many :comments, :dependent => :destroy
  belongs_to :user

  scope :rating, where("rating > ?", 0)

   def self.count_content
   	where("length(description) > 100")
  end

  validate :valid_title
  validates :title, 
    		:presence => { :message => "can't be blank, must be filled" },
            :uniqueness => true,
            :allow_nil => false,
            :allow_blank => false

  validates :description,
    		:presence => { :message => "can't be blank, must be filled" },
            :allow_nil => false,
            :allow_blank => false
            
  validates :user_id,
    		:presence => { :message => "can't be blank, must be filled" },
            :allow_nil => false,
            :allow_blank => false

  validates :rating,
    		:presence => { :message => "can't be blank, must be filled" },
            :allow_nil => false,
            :allow_blank => false

  def valid_title
   		self.errors[:title] << "can't left blank" if (title == 'nill' || title == 'empty' || title == 'blank')
 	end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
	before_filter :require_admin_login

	def index
    	@articles = Article.all
  	end

  	def show
      	@articles = Article.find(params[:id])
      	@by = @articles.user_id
      	@user = User.find_by_id(@by)
        @comments = Comment.find_all_by_article_id(params[:id])
        @comment  = Comment.new
   	end

	  def new
    	@articles = Article.new
  	end

  	def create
      	@articles = Article.new(params[:article])
      	if @articles.save
           flash[:notice] = 'Article was successfully created.'
            redirect_to :action => 'index'
     	 else
            flash[:error] = 'Article was failed to create.'
            render :action => 'new'
      	end
   	end

  	def edit
      	@article = Article.find(params[:id])
   	end	
  	
  	def update
      	@article = Article.find(params[:id])
      	if @article.update_attributes(params[:article])
           flash[:notice] = 'Article was successfully updated.'
         	redirect_to :action => 'show', :id => @article
      	else
          flash[:error] = 'Article was failed to update.'
         	render :action => 'edit'
      	end
   	end

  	def destroy
      @article = Article.find(params[:id])
        @article.destroy
        redirect_to :action => 'index'
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :require_login, :only => [:new, :create, :edit, :update, :destroy]

	  def index
    	@articles = Article.find_all_by_user_id(session[:user_id])
  	end

  	def show
      	@articles = Article.find(params[:id])
      	@by = @articles.user_id
      	@user = User.find_by_id(@by)
        @comments = Comment.find_all_by_article_id(params[:id])
        @comment  = Comment.new
   	end

	  def new
    	@articles = Article.new
  	end

  	def create
      	@articles = Article.new(params[:article])
      	if @articles.save
           flash[:notice] = 'Article was successfully created.'
            redirect_to :action => 'index'
     	 else
            flash[:error] = 'Article was failed to create.'
            render :action => 'new'
      	end
   	end

  	def edit
      	@article = Article.find(params[:id])
   	end	
  	
  	def update
      	@article = Article.find(params[:id])
      	if @article.update_attributes(params[:article])
           flash[:notice] = 'Article was successfully updated.'
         	redirect_to :action => 'show', :id => @article
      	else
          flash[:error] = 'Article was failed to update.'
         	render :action => 'edit'
      	end
   	end

  	def destroy
      @article = Article.find(params[:id])
      if @article.user_id == session[:user_id]
        @article.destroy
        redirect_to :action => 'index'
      else
        flash[:notice] = "Article can't be deleted"
        redirect_to :action => 'index'
    end
   end

end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_comments.html.erb
<% comments.each do |comment| %>
  <%= comment.content %><br />
<% end %>

app/views/articles/edit.html.erb
<% if @article.errors.any? %>
  <div id="errorExplanation">
    <h2>
       <%= pluralize(@article.errors.count, "error") %> prohibited this user from being saved:
    </h2>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p>
<table>
	<%= form_for @article do |f| %>  
  	<tr>
  		<td>title: </td>
  		<td><%= f.text_field :title %> </td>
  	</tr>
  	<tr>
  		<td>rating : </td>
  		<td> <%= f.text_field :rating %> </td>
  	</tr>
  	<tr>
  		<td>user_id : </td>
  		<td> <%= f.text_field :user_id %> </td>
  	</tr>
  	<tr>
  		<td>description : </td>
  		<td> <%= text_area :article, :description %></td>
  	</tr>
  	<tr>
  		<td><%=f.submit :update %></td>
  	</tr>
	<% end %>
</table>

app/views/articles/index.html.erb
<%= flash[:notice] %>

<% if @articles.blank? %>
<p>There are not any Articles currently in the system.</p>

<% else %>

<p>These are the current Articles in our system</p>

	<p><%= link_to "Add new Article", {:action => 'new' }%></p>

	<table border="1" cellpadding="8px" cellspacing="0">

	<% @articles.each do |c| %>
		<tr>
			<td width="70%"><%= link_to c.title, {:action => "show", :id => c.id} -%> </td>
			<td><%= link_to ' Edit ', {:action => "edit", :id => c.id} %> </td>
			<td><%= link_to ' Delete ', {:action => "destroy", :id => c.id}, :method => :delete, :confirm => "Are you sure you want to delete this item?" %> </td>
		</tr>
	<% end %>

	</table>
<% end %>

app/views/articles/new.html.erb
<%= flash[:error] %>

<% if @articles.errors.any? %>
  <div id="errorExplanation">
    <h2>
       <%= pluralize(@articles.errors.count, "error") %> prohibited this user from being saved:
    </h2>
    <ul>
      <% @articles.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p>

<table>

	<%= form_for @articles do |f| %>  
  	<tr>
  		<td>title: </td>
  		<td> <%= f.text_field :title %>  </td>
  	</tr>
  	<tr>
  		<td>rating : </td>
  		<td><%= f.text_field :rating %> </td>
  	</tr>
  	<tr>
  		<td>user_id : </td>
  		<td><%= f.text_field :user_id %> </td>
  	</tr>
  	<tr>
  		<td>description : </td>
  		<td><%= text_area :article, :description %> </td>
  	</tr>
  	<tr>
  		<td><%=f.submit :create %> </td>
  	</tr>
<% end %>

</table>

app/views/articles/show.html.erb
<table>
	<tr>
		<td colspan="2"><h1><%= @articles.title %></h1></td>
	</tr>
	<tr>
		<td  width="15%"><strong>Origin </td><td></strong> : <%= @user.first_name %> <%= @user.last_name %></td>
	</tr>
	<tr>
		<td><strong>Rating </td><td></strong> : <%= @articles.rating %></td>
	</tr>
	<tr>
		<td><strong>Created Date </td><td> :</strong> <%= @articles.created_at %></td>
	</tr>
	<tr>
		<td colspan="2"> <p><%= @articles.description %></p></td>
	</tr>
	<tr>
		<td><p><%= link_to "Back", {:action => 'index' }%></p></td>
	</tr>

</table>

<ul>
<div id="comments">
  <%= render :partial => "comments", :locals => {:comments => @comments}  %>
</div>
</ul>

<% unless(current_user.nil?)%>
	<h2>Add Comment</h2>
   <%= form_for @comment, :url => comments_path, :remote => true do |f| -%>
      	<%= f.text_area :content, size: "60x5"%>
		<%= f.hidden_field :user_id, :value => current_user.id %>
		<%= f.hidden_field :article_id, :value => @articles.id %><br />
      <%= submit_tag "comment" %>
  <% end -%>
<% end %>